### ISSUE TITLE
invalid ca certificate

### ISSUE THREAD

**Issue by grzs** [robertdebock/ansible-role-ca#2]
## Describe the bug

I used this role as a dependency of your openvpn role.
Everything went as expected but I can't connect to the server via Tunnelblick from my macbook,
because it claims about the self signed certificate of the server.
It seems to me that the ca cert had built without the isCA bit set.
So it's not a real bug, but maybe a conceptional mistake(?) as the ca is unable to generate valid certificates this way.
Or I don't understand the concept...

## Playbook

```yaml
---
- name: install openvpn server
  hosts: vpn
  become: yes
  gather_facts: yes
  vars_files:
    - ca-vars.yml # company, department, etc
  remote_user: "{{ default_user }}"

  vars:
    openvpn_server: yes
    openvpn_client: yes
    openvpn_client_server: "{{ ansible_host }}"

  pre_tasks:
    - name: Generate an OpenSSL certificate signed with your own CA certificate
      openssl_certificate:
        path: /etc/ssl/certs/client.crt
        csr_path: /etc/ssl/client.csr
	ownca_path: /etc/ssl/certs/ca.crt
        ownca_privatekey_path: /etc/ssl/private/ca.pem
        ownca_privatekey_passphrase: *******
        provider: ownca

  roles:
    - role: robertdebock.openvpn
```

## Output

Tunnelblick log:
VERIFY ERROR: depth=0, error=self signed certificate: CN=server

cert verification output:
```bash
$ openssl verify -CAfile /etc/openvpn/certs/ca.crt /etc/openvpn/certs/server.crt 
CN = server
error 18 at 0 depth lookup: self signed certificate
error /etc/openvpn/certs/server.crt: verification failed
```

After I tried to generate a client certificate with the openssl_certificate module with ownca provider and previously generated client key and csr,
It's still invalid according to the verify output:
```bash
$ openssl verify -CAfile certs/ca.crt certs/client.crt
C = HU, ST = Budapest, O = ******, OU = IT, CN = ca.mydomain.hu, emailAddress = admin@mydomain.hu
error 24 at 1 depth lookup: invalid CA certificate
error certs/client.crt: verification failed
```

## Environment

- Control node OS: Mac os
- Control node Ansible version: 2.9.10
- Managed node OS: Debian 10

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).
