### ISSUE TITLE
Issues with Ansible 2.10+

### ISSUE THREAD

**Issue by Chilinot** [robertdebock/ansible-role-ca#8]
## Describe the bug
Trying to deploy this role on a CentOS 8 server, with ansible 2.10.5 and getting this error:
```
TASK [robertdebock.ca : generate ca key] ******************************************************************
fatal: [xxx]: FAILED! => {"changed": false, "msg": "Cryptography backend can only use \"auto\" for cipher option."}
```

Looking into the module that [failed](https://docs.ansible.com/ansible/latest/collections/community/crypto/openssl_privatekey_module.html) you can see the following in its documentation for the `cipher` param:
> The cipher to encrypt the private key. (Valid values can be found by running `openssl list -cipher-algorithms` or `openssl list-cipher-algorithms`, depending on your OpenSSL version.) When using the cryptography backend, use auto.

Later for the `select_crypto_backend` param this is documented:
> Please note that the pyopenssl backend has been deprecated in Ansible 2.9, and will be removed in community.crypto 2.0.0. From that point on, only the cryptography backend will be available.

## Playbook

```yaml
    - role: robertdebock.ca
      tags:
        - ca
      vars:
        ca_passphrase: xxxx
        ca_common_name: xxxx.com
        ca_country_name: xx
        ca_email_address: xxxx
        ca_organization_name: xxx
        ca_organizational_unit_name: xx
        ca_state_or_province_name: xxx
        ca_locality_name: xxxx
        ca_requests:
          - xxxx.com
```

## Requirements file

```yaml
  - role: robertdebock.ca
    version: 4.0.6
```

## Environment

- Control node OS: `MacOS Big Sur`
- Control node Ansible version: `2.10.5`
- Managed node OS: `CentOS 8`
